import Mathlib.Data.Fin.Basic

/-!
# Van der Waerden lower-bound certificates (data)

Explicit 2-colorings with no long monochromatic arithmetic progression:
* w26data - 1131 cells, no monochromatic 6-AP: certifies W(2,6) >= 1132,
  the lower half of the exact value (Kouril-Paul 2008).
* w27data - 3703 cells, no monochromatic 7-AP: certifies W(2,7) > 3703,
  matching the published record (Rabung-Lotts, E-JC 19(2) #P35).

Provenance: cyclic base patterns (periods 226 and 617) from Marijn Heule
certificate collection (github.com/marijnheule/vdWaerden), unrolled to full
published length with one boundary symbol flipped (phases 112 and 616; the
flip removes the single wraparound progression whose difference equals the
period). Independently verified, with negative controls, by
computations/vanderwaerden/verify_cert.py.
-/

namespace OpenProblems.VanDerWaerden

def w26data : Array Bool :=
  #[false, true, false, false, false, false, true, true, false, true, true, true, true, true,
  false, true, false, false, false, false, true, false, false, false, true, true, false, false,
  false, false, false, true, false, false, true, false, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, false, true, false, true, true, false,
  false, true, true, false, false, true, false, true, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, true, false, true, true, false, true,
  true, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
  true, false, false, false, false, false, true, false, false, true, true, true, true, false,
  false, false, true, true, true, true, false, false, true, false, false, false, false, false,
  true, false, true, true, true, true, false, true, true, true, false, false, true, true, true,
  true, true, false, true, true, false, true, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, true, false, true, false, false, true, true,
  false, false, true, true, false, true, false, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, false, true, false, false, true, false, false,
  false, false, false, true, true, false, false, false, true, false, false, false, false, true,
  false, true, true, true, true, true, false, true, true, false, false, false, false, true,
  true, true, false, false, false, false, true, true, false, true, true, true, true, true,
  false, true, false, false, false, false, true, false, false, false, true, true, false, false,
  false, false, false, true, false, false, true, false, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, false, true, false, true, true, false,
  false, true, true, false, false, true, false, true, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, true, false, true, true, false, true,
  true, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
  true, false, false, false, false, false, true, false, false, true, true, true, true, false,
  false, false, true, true, true, true, false, false, true, false, false, false, false, false,
  true, false, true, true, true, true, false, true, true, true, false, false, true, true, true,
  true, true, false, true, true, false, true, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, true, false, true, false, false, true, true,
  false, false, true, true, false, true, false, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, false, true, false, false, true, false, false,
  false, false, false, true, true, false, false, false, true, false, false, false, false, true,
  false, true, true, true, true, true, false, true, true, false, false, false, false, true,
  true, true, false, false, false, false, true, true, false, true, true, true, true, true,
  false, true, false, false, false, false, true, false, false, false, true, true, false, false,
  false, false, false, true, false, false, true, false, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, false, true, false, true, true, false,
  false, true, true, false, false, true, false, true, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, true, false, true, true, false, true,
  true, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
  true, false, false, false, false, false, true, false, false, true, true, true, true, false,
  false, false, true, true, true, true, false, false, true, false, false, false, false, false,
  true, false, true, true, true, true, false, true, true, true, false, false, true, true, true,
  true, true, false, true, true, false, true, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, true, false, true, false, false, true, true,
  false, false, true, true, false, true, false, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, false, true, false, false, true, false, false,
  false, false, false, true, true, false, false, false, true, false, false, false, false, true,
  false, true, true, true, true, true, false, true, true, false, false, false, false, true,
  true, true, false, false, false, false, true, true, false, true, true, true, true, true,
  false, true, false, false, false, false, true, false, false, false, true, true, false, false,
  false, false, false, true, false, false, true, false, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, false, true, false, true, true, false,
  false, true, true, false, false, true, false, true, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, true, false, true, true, false, true,
  true, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
  true, false, false, false, false, false, true, false, false, true, true, true, true, false,
  false, false, true, true, true, true, false, false, true, false, false, false, false, false,
  true, false, true, true, true, true, false, true, true, true, false, false, true, true, true,
  true, true, false, true, true, false, true, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, true, false, true, false, false, true, true,
  false, false, true, true, false, true, false, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, false, true, false, false, true, false, false,
  false, false, false, true, true, false, false, false, true, false, false, false, false, true,
  false, true, true, true, true, true, false, true, true, false, false, false, false, true,
  true, true, false, false, false, false, true, true, false, true, true, true, true, true,
  false, true, false, false, false, false, true, false, false, false, true, true, false, false,
  false, false, false, true, false, false, true, false, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, false, true, false, true, true, false,
  false, true, true, false, false, true, false, true, false, false, true, false, true, true,
  true, false, false, false, true, false, true, true, true, false, true, true, false, true,
  true, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
  true, false, false, false, false, false, true, false, false, true, true, true, true, false,
  false, false, true, true, true, true, false, false, true, false, false, false, false, false,
  true, false, true, true, true, true, false, true, true, true, false, false, true, true, true,
  true, true, false, true, true, false, true, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, true, false, true, false, false, true, true,
  false, false, true, true, false, true, false, true, true, false, true, false, false, false,
  true, true, true, false, true, false, false, false, true, false, false, true, false, false,
  false, false, false, true, true, false, false, false, true, false, false, false, false, true,
  false, true, true, true, true, true, false, true, true, false, false, false, false, true,
  true]

def w27data : Array Bool :=
  #[false, false, false, true, false, true, true, false, false, false, true, false, true, true,
  false, false, false, true, false, false, true, true, false, true, true, false, true, true,
  false, true, false, false, false, true, true, true, false, false, false, false, true, false,
  true, false, false, true, true, false, true, false, false, false, true, true, true, true,
  false, true, true, false, false, true, false, false, false, false, true, false, true, false,
  true, false, false, true, false, true, false, false, false, false, true, false, false, false,
  true, false, false, false, false, true, true, true, true, true, false, true, true, false,
  false, false, false, true, false, true, true, false, true, true, true, true, true, true,
  false, false, true, false, true, true, false, true, false, false, true, true, false, true,
  false, true, false, true, false, true, true, false, false, false, true, false, false, true,
  true, true, false, true, false, false, true, true, false, true, true, true, false, true,
  false, true, false, false, false, false, true, true, false, true, false, false, false, false,
  true, false, false, false, false, true, false, false, false, true, true, false, true, true,
  true, false, true, true, true, true, false, true, true, true, true, true, false, true, false,
  false, false, false, false, true, true, true, false, true, true, true, true, false, false,
  true, true, true, true, true, true, false, true, false, true, false, true, false, false,
  false, false, true, true, false, false, true, true, true, true, true, false, true, true, true,
  false, false, false, true, true, true, true, true, false, true, true, false, false, true,
  true, true, false, true, true, false, false, true, true, true, true, false, false, false,
  false, false, false, true, true, false, false, false, false, false, true, false, true, true,
  true, false, false, false, true, false, false, false, false, true, true, false, true, true,
  false, true, true, false, true, false, true, false, false, false, true, true, false, false,
  true, true, false, false, false, true, false, true, false, true, true, false, true, true,
  false, true, true, false, false, false, false, true, false, false, false, true, true, true,
  false, true, false, false, false, false, false, true, true, false, false, false, false, false,
  false, true, true, true, true, false, false, true, true, false, true, true, true, false,
  false, true, true, false, true, true, true, true, true, false, false, false, true, true, true,
  false, true, true, true, true, true, false, false, true, true, false, false, false, false,
  true, false, true, false, true, false, true, true, true, true, true, true, false, false, true,
  true, true, true, false, true, true, true, false, false, false, false, false, true, false,
  true, true, true, true, true, false, true, true, true, true, false, true, true, true, false,
  true, true, false, false, false, true, false, false, false, false, true, false, false, false,
  false, true, false, true, true, false, false, false, false, true, false, true, false, true,
  true, true, false, true, true, false, false, true, false, true, true, true, false, false,
  true, false, false, false, true, true, false, true, false, true, false, true, false, true,
  true, false, false, true, false, true, true, false, true, false, false, true, true, true,
  true, true, true, false, true, true, false, true, false, false, false, false, true, true,
  false, true, true, true, true, true, false, false, false, false, true, false, false, false,
  true, false, false, false, false, true, false, true, false, false, true, false, true, false,
  true, false, false, false, false, true, false, false, true, true, false, true, true, true,
  true, false, false, false, true, false, true, true, false, false, true, false, true, false,
  false, false, false, true, true, true, false, false, false, true, false, true, true, false,
  true, true, false, true, true, false, false, true, false, false, false, true, true, false,
  true, false, false, false, true, true, false, true, false, false, true, false, false, true,
  false, true, true, false, false, false, true, false, true, true, false, false, false, true,
  false, false, true, true, false, true, true, false, true, true, false, true, false, false,
  false, true, true, true, false, false, false, false, true, false, true, false, false, true,
  true, false, true, false, false, false, true, true, true, true, false, true, true, false,
  false, true, false, false, false, false, true, false, true, false, true, false, false, true,
  false, true, false, false, false, false, true, false, false, false, true, false, false, false,
  false, true, true, true, true, true, false, true, true, false, false, false, false, true,
  false, true, true, false, true, true, true, true, true, true, false, false, true, false, true,
  true, false, true, false, false, true, true, false, true, false, true, false, true, false,
  true, true, false, false, false, true, false, false, true, true, true, false, true, false,
  false, true, true, false, true, true, true, false, true, false, true, false, false, false,
  false, true, true, false, true, false, false, false, false, true, false, false, false, false,
  true, false, false, false, true, true, false, true, true, true, false, true, true, true, true,
  false, true, true, true, true, true, false, true, false, false, false, false, false, true,
  true, true, false, true, true, true, true, false, false, true, true, true, true, true, true,
  false, true, false, true, false, true, false, false, false, false, true, true, false, false,
  true, true, true, true, true, false, true, true, true, false, false, false, true, true, true,
  true, true, false, true, true, false, false, true, true, true, false, true, true, false,
  false, true, true, true, true, false, false, false, false, false, false, true, true, false,
  false, false, false, false, true, false, true, true, true, false, false, false, true, false,
  false, false, false, true, true, false, true, true, false, true, true, false, true, false,
  true, false, false, false, true, true, false, false, true, true, false, false, false, true,
  false, true, false, true, true, false, true, true, false, true, true, false, false, false,
  false, true, false, false, false, true, true, true, false, true, false, false, false, false,
  false, true, true, false, false, false, false, false, false, true, true, true, true, false,
  false, true, true, false, true, true, true, false, false, true, true, false, true, true, true,
  true, true, false, false, false, true, true, true, false, true, true, true, true, true, false,
  false, true, true, false, false, false, false, true, false, true, false, true, false, true,
  true, true, true, true, true, false, false, true, true, true, true, false, true, true, true,
  false, false, false, false, false, true, false, true, true, true, true, true, false, true,
  true, true, true, false, true, true, true, false, true, true, false, false, false, true,
  false, false, false, false, true, false, false, false, false, true, false, true, true, false,
  false, false, false, true, false, true, false, true, true, true, false, true, true, false,
  false, true, false, true, true, true, false, false, true, false, false, false, true, true,
  false, true, false, true, false, true, false, true, true, false, false, true, false, true,
  true, false, true, false, false, true, true, true, true, true, true, false, true, true, false,
  true, false, false, false, false, true, true, false, true, true, true, true, true, false,
  false, false, false, true, false, false, false, true, false, false, false, false, true, false,
  true, false, false, true, false, true, false, true, false, false, false, false, true, false,
  false, true, true, false, true, true, true, true, false, false, false, true, false, true,
  true, false, false, true, false, true, false, false, false, false, true, true, true, false,
  false, false, true, false, true, true, false, true, true, false, true, true, false, false,
  true, false, false, false, true, true, false, true, false, false, false, true, true, false,
  true, false, false, true, false, false, true, false, true, true, false, false, false, true,
  false, true, true, false, false, false, true, false, false, true, true, false, true, true,
  false, true, true, false, true, false, false, false, true, true, true, false, false, false,
  false, true, false, true, false, false, true, true, false, true, false, false, false, true,
  true, true, true, false, true, true, false, false, true, false, false, false, false, true,
  false, true, false, true, false, false, true, false, true, false, false, false, false, true,
  false, false, false, true, false, false, false, false, true, true, true, true, true, false,
  true, true, false, false, false, false, true, false, true, true, false, true, true, true,
  true, true, true, false, false, true, false, true, true, false, true, false, false, true,
  true, false, true, false, true, false, true, false, true, true, false, false, false, true,
  false, false, true, true, true, false, true, false, false, true, true, false, true, true,
  true, false, true, false, true, false, false, false, false, true, true, false, true, false,
  false, false, false, true, false, false, false, false, true, false, false, false, true, true,
  false, true, true, true, false, true, true, true, true, false, true, true, true, true, true,
  false, true, false, false, false, false, false, true, true, true, false, true, true, true,
  true, false, false, true, true, true, true, true, true, false, true, false, true, false, true,
  false, false, false, false, true, true, false, false, true, true, true, true, true, false,
  true, true, true, false, false, false, true, true, true, true, true, false, true, true, false,
  false, true, true, true, false, true, true, false, false, true, true, true, true, false,
  false, false, false, false, false, true, true, false, false, false, false, false, true, false,
  true, true, true, false, false, false, true, false, false, false, false, true, true, false,
  true, true, false, true, true, false, true, false, true, false, false, false, true, true,
  false, false, true, true, false, false, false, true, false, true, false, true, true, false,
  true, true, false, true, true, false, false, false, false, true, false, false, false, true,
  true, true, false, true, false, false, false, false, false, true, true, false, false, false,
  false, false, false, true, true, true, true, false, false, true, true, false, true, true,
  true, false, false, true, true, false, true, true, true, true, true, false, false, false,
  true, true, true, false, true, true, true, true, true, false, false, true, true, false, false,
  false, false, true, false, true, false, true, false, true, true, true, true, true, true,
  false, false, true, true, true, true, false, true, true, true, false, false, false, false,
  false, true, false, true, true, true, true, true, false, true, true, true, true, false, true,
  true, true, false, true, true, false, false, false, true, false, false, false, false, true,
  false, false, false, false, true, false, true, true, false, false, false, false, true, false,
  true, false, true, true, true, false, true, true, false, false, true, false, true, true, true,
  false, false, true, false, false, false, true, true, false, true, false, true, false, true,
  false, true, true, false, false, true, false, true, true, false, true, false, false, true,
  true, true, true, true, true, false, true, true, false, true, false, false, false, false,
  true, true, false, true, true, true, true, true, false, false, false, false, true, false,
  false, false, true, false, false, false, false, true, false, true, false, false, true, false,
  true, false, true, false, false, false, false, true, false, false, true, true, false, true,
  true, true, true, false, false, false, true, false, true, true, false, false, true, false,
  true, false, false, false, false, true, true, true, false, false, false, true, false, true,
  true, false, true, true, false, true, true, false, false, true, false, false, false, true,
  true, false, true, false, false, false, true, true, false, true, false, false, true, false,
  false, true, false, true, true, false, false, false, true, false, true, true, false, false,
  false, true, false, false, true, true, false, true, true, false, true, true, false, true,
  false, false, false, true, true, true, false, false, false, false, true, false, true, false,
  false, true, true, false, true, false, false, false, true, true, true, true, false, true,
  true, false, false, true, false, false, false, false, true, false, true, false, true, false,
  false, true, false, true, false, false, false, false, true, false, false, false, true, false,
  false, false, false, true, true, true, true, true, false, true, true, false, false, false,
  false, true, false, true, true, false, true, true, true, true, true, true, false, false, true,
  false, true, true, false, true, false, false, true, true, false, true, false, true, false,
  true, false, true, true, false, false, false, true, false, false, true, true, true, false,
  true, false, false, true, true, false, true, true, true, false, true, false, true, false,
  false, false, false, true, true, false, true, false, false, false, false, true, false, false,
  false, false, true, false, false, false, true, true, false, true, true, true, false, true,
  true, true, true, false, true, true, true, true, true, false, true, false, false, false,
  false, false, true, true, true, false, true, true, true, true, false, false, true, true, true,
  true, true, true, false, true, false, true, false, true, false, false, false, false, true,
  true, false, false, true, true, true, true, true, false, true, true, true, false, false,
  false, true, true, true, true, true, false, true, true, false, false, true, true, true, false,
  true, true, false, false, true, true, true, true, false, false, false, false, false, false,
  true, true, false, false, false, false, false, true, false, true, true, true, false, false,
  false, true, false, false, false, false, true, true, false, true, true, false, true, true,
  false, true, false, true, false, false, false, true, true, false, false, true, true, false,
  false, false, true, false, true, false, true, true, false, true, true, false, true, true,
  false, false, false, false, true, false, false, false, true, true, true, false, true, false,
  false, false, false, false, true, true, false, false, false, false, false, false, true, true,
  true, true, false, false, true, true, false, true, true, true, false, false, true, true,
  false, true, true, true, true, true, false, false, false, true, true, true, false, true, true,
  true, true, true, false, false, true, true, false, false, false, false, true, false, true,
  false, true, false, true, true, true, true, true, true, false, false, true, true, true, true,
  false, true, true, true, false, false, false, false, false, true, false, true, true, true,
  true, true, false, true, true, true, true, false, true, true, true, false, true, true, false,
  false, false, true, false, false, false, false, true, false, false, false, false, true, false,
  true, true, false, false, false, false, true, false, true, false, true, true, true, false,
  true, true, false, false, true, false, true, true, true, false, false, true, false, false,
  false, true, true, false, true, false, true, false, true, false, true, true, false, false,
  true, false, true, true, false, true, false, false, true, true, true, true, true, true, false,
  true, true, false, true, false, false, false, false, true, true, false, true, true, true,
  true, true, false, false, false, false, true, false, false, false, true, false, false, false,
  false, true, false, true, false, false, true, false, true, false, true, false, false, false,
  false, true, false, false, true, true, false, true, true, true, true, false, false, false,
  true, false, true, true, false, false, true, false, true, false, false, false, false, true,
  true, true, false, false, false, true, false, true, true, false, true, true, false, true,
  true, false, false, true, false, false, false, true, true, false, true, false, false, false,
  true, true, false, true, false, false, true, false, false, true, false, true, true, false,
  false, false, true, false, true, true, false, false, false, true, false, false, true, true,
  false, true, true, false, true, true, false, true, false, false, false, true, true, true,
  false, false, false, false, true, false, true, false, false, true, true, false, true, false,
  false, false, true, true, true, true, false, true, true, false, false, true, false, false,
  false, false, true, false, true, false, true, false, false, true, false, true, false, false,
  false, false, true, false, false, false, true, false, false, false, false, true, true, true,
  true, true, false, true, true, false, false, false, false, true, false, true, true, false,
  true, true, true, true, true, true, false, false, true, false, true, true, false, true, false,
  false, true, true, false, true, false, true, false, true, false, true, true, false, false,
  false, true, false, false, true, true, true, false, true, false, false, true, true, false,
  true, true, true, false, true, false, true, false, false, false, false, true, true, false,
  true, false, false, false, false, true, false, false, false, false, true, false, false, false,
  true, true, false, true, true, true, false, true, true, true, true, false, true, true, true,
  true, true, false, true, false, false, false, false, false, true, true, true, false, true,
  true, true, true, false, false, true, true, true, true, true, true, false, true, false, true,
  false, true, false, false, false, false, true, true, false, false, true, true, true, true,
  true, false, true, true, true, false, false, false, true, true, true, true, true, false, true,
  true, false, false, true, true, true, false, true, true, false, false, true, true, true, true,
  false, false, false, false, false, false, true, true, false, false, false, false, false, true,
  false, true, true, true, false, false, false, true, false, false, false, false, true, true,
  false, true, true, false, true, true, false, true, false, true, false, false, false, true,
  true, false, false, true, true, false, false, false, true, false, true, false, true, true,
  false, true, true, false, true, true, false, false, false, false, true, false, false, false,
  true, true, true, false, true, false, false, false, false, false, true, true, false, false,
  false, false, false, false, true, true, true, true, false, false, true, true, false, true,
  true, true, false, false, true, true, false, true, true, true, true, true, false, false,
  false, true, true, true, false, true, true, true, true, true, false, false, true, true, false,
  false, false, false, true, false, true, false, true, false, true, true, true, true, true,
  true, false, false, true, true, true, true, false, true, true, true, false, false, false,
  false, false, true, false, true, true, true, true, true, false, true, true, true, true, false,
  true, true, true, false, true, true, false, false, false, true, false, false, false, false,
  true, false, false, false, false, true, false, true, true, false, false, false, false, true,
  false, true, false, true, true, true, false, true, true, false, false, true, false, true,
  true, true, false, false, true, false, false, false, true, true, false, true, false, true,
  false, true, false, true, true, false, false, true, false, true, true, false, true, false,
  false, true, true, true, true, true, true, false, true, true, false, true, false, false,
  false, false, true, true, false, true, true, true, true, true, false, false, false, false,
  true, false, false, false, true, false, false, false, false, true, false, true, false, false,
  true, false, true, false, true, false, false, false, false, true, false, false, true, true,
  false, true, true, true, true, false, false, false, true, false, true, true, false, false,
  true, false, true, false, false, false, false, true, true, true, false, false, false, true,
  false, true, true, false, true, true, false, true, true, false, false, true, false, false,
  false, true, true, false, true, false, false, false, true, true, false, true, false, false,
  true, false, false, true, false, true, true, false, false, false, true, false, true, true,
  false, false, false, true, false, false, true, true, false, true, true, false, true, true,
  false, true, false, false, false, true, true, true, false, false, false, false, true, false,
  true, false, false, true, true, false, true, false, false, false, true, true, true, true,
  false, true, true, false, false, true, false, false, false, false, true, false, true, false,
  true, false, false, true, false, true, false, false, false, false, true, false, false, false,
  true, false, false, false, false, true, true, true, true, true, false, true, true, false,
  false, false, false, true, false, true, true, false, true, true, true, true, true, true,
  false, false, true, false, true, true, false, true, false, false, true, true, false, true,
  false, true, false, true, false, true, true, false, false, false, true, false, false, true,
  true, true, false, true, false, false, true, true, false, true, true, true, false, true,
  false, true, false, false, false, false, true, true, false, true, false, false, false, false,
  true, false, false, false, false, true, false, false, false, true, true, false, true, true,
  true, false, true, true, true, true, false, true, true, true, true, true, false, true, false,
  false, false, false, false, true, true, true, false, true, true, true, true, false, false,
  true, true, true, true, true, true, false, true, false, true, false, true, false, false,
  false, false, true, true, false, false, true, true, true, true, true, false, true, true, true,
  false, false, false, true, true, true, true, true, false, true, true, false, false, true,
  true, true, false, true, true, false, false, true, true, true, true, false, false, false,
  false, false, false, true, true, false, false, false, false, false, true, false, true, true,
  true, false, false, false, true, false, false, false, false, true, true, false, true, true,
  false, true, true, false, true, false, true, false, false, false, true, true, false, false,
  true, true, false, false, false, true, false, true, false, true, true, false, true, true,
  false, true, true, false, false, false, false, true, false, false, false, true, true, true,
  false, true, false, false, false, false, false, true, true, false, false, false, false, false,
  false, true, true, true, true, false, false, true, true, false, true, true, true, false,
  false, true, true, false, true, true, true, true, true, false, false, false, true, true, true,
  false, true, true, true, true, true, false, false, true, true, false, false, false, false,
  true, false, true, false, true, false, true, true, true, true, true, true, false, false, true,
  true, true, true, false, true, true, true, false, false, false, false, false, true, false,
  true, true, true, true, true, false, true, true, true, true, false, true, true, true, false,
  true, true, false, false, false, true, false, false, false, false, true, false, false, false,
  false, true, false, true, true, false, false, false, false, true, false, true, false, true,
  true, true, false, true, true, false, false, true, false, true, true, true, false, false,
  true, false, false, false, true, true, false, true, false, true, false, true, false, true,
  true, false, false, true, false, true, true, false, true, false, false, true, true, true,
  true, true, true, false, true, true, false, true, false, false, false, false, true, true,
  false, true, true, true, true, true, false, false, false, false, true, false, false, false,
  true, false, false, false, false, true, false, true, false, false, true, false, true, false,
  true, false, false, false, false, true, false, false, true, true, false, true, true, true,
  true, false, false, false, true, false, true, true, false, false, true, false, true, false,
  false, false, false, true, true, true, false, false, false, true, false, true, true, false,
  true, true, false, true, true, false, false, true, false, false, false, true, true, false,
  true, false, false, false, true, true, false, true, false, false, true]

end OpenProblems.VanDerWaerden
